export const primaryColor =  '#ff0000'
export const whiteColor =  '#ffffff'
export const inputColor =  '#d9d9d9'
export const blackColor =  '#151823'
export const greenColor =  '#008b0c'
export const grayTitleColor = '#605e5e'